"""Separeted Admins from User Table changes

Revision ID: 3c852253ffdc
Revises: 
Create Date: 2023-11-05 16:41:30.091883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c852253ffdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_admin_username', ['username'])
        # No need to drop the foreign key constraint since it doesn't exist
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=50), nullable=True))

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        # No need to recreate the foreign key constraint since it was removed
        batch_op.drop_constraint('uq_admin_username', type_='unique')

    # ### end Alembic commands ###
